<?xml version="1.0" encoding="utf-8"?><Database Name="EmployeeTracking" Class="DataDepartmentDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-KD1BG1RK\SQLEXPRESS;Initial Catalog=EmployeeTracking;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="EmployeeTrackingConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DEPARTEMENT" Member="DEPARTEMENTs">
    <Type Name="DEPARTEMENT">
      <Column Name="DepartmentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Department" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>